import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"])

import { Inter, Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});



export const metadata = {
  title: "Life Sizzle",
  description: "Generated by social media base",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#FFFFFF]">

        {children}

      </body>
    </html>
  );
}
